In [8]:
import pandas as pd

import numpy as np

import os

import re

In [9]:
df = pd.read_csv('FY 20 Solution COMPLETE Dec 2.csv')

df = df.groupby(['PI','Types']).sum()

df = df.drop(columns=['Totals', 'IDs'])

df = df.rename(columns={"Amounts": "Amounts Due"})

#df.to_csv('FY20 Totals PI Types Dec 2.csv')

df

                                  Amounts Due
PI              Types
Cronin          RUDICS                6461.73
Cross           RUDICS                2291.21
Dziak           Non-RUDICS             566.98
                RUDICS                 725.35
Feely           RUDICS                1989.21
                SHORT BURST DATA       356.66
Johnson         RUDICS               85687.31
                SHORT BURST DATA       380.81
Klinck          RUDICS                 276.74
McPhaden        RUDICS               27192.86
                SHORT BURST DATA      3232.67
Meinig          SHORT BURST DATA       778.16
Meinig Chaba    RUDICS                 181.03
Meinig DART     RUDICS                2435.97
                RUDICS VOICE           570.37
                SHORT BURST DATA       972.49
Meinig GNSS GPS SHORT BURST DATA       161.58
Meinig ITAE     RUDICS                2446.38
                SHORT BURST DATA       161.58
Meinig SPURS2   RUDICS                2015.75
                SHORT BURST DATA       323.16
Stabeno         SHORT BURST DATA      2387.87
Sutton          Non-RUDICS             641.90
                RUDICS               29396.21
                SHORT BURST DATA      1478.33

In [14]:
df.sum(axis = 0, skipna = True)

Amounts Due    173112.31
dtype: float64