# FY21 Concanted PI Totals Files Collection 1 Revised

In [2]:
import os
import glob
import pandas as pd
os.chdir("./FY21 PI Totals")

In [3]:
extension = 'xlsx'
all_filenames = [i for i in glob.glob('*.{}'.format(extension))]
#combine all files in the list
combined_excel = pd.concat([pd.read_excel(f) for f in all_filenames ])
#export to csv
combined_excel.to_excel( "all_data_pi_totals collection 1.xlsx", index=False)

In [6]:
df = pd.read_excel( "all_data_pi_totals collection 1.xlsx")
df = df.groupby(['PI']).sum()
df['FY 21 Collection 1 Totals'] = df.iloc[:, 0:14].sum(axis=1)
df.to_excel('FY 21 INMARSAT Collection 1 Totals PI Type.xlsx')
df

,3 DEC'20 Amounts Due,4 Jan'21 Amounts Due,2 NOV'20 Amounts Due,1 Oct'20 Amounts Due,FY 21 Collection 1 Totals
PI,,,,,
Cronin,339.91,300.91,334.41,365.66,1340.89
Cross,191.21,175.21,176.21,218.96,761.59
Dziak,63.43,63.43,63.43,63.43,253.72
Feely,146.23,122.98,164.19,157.19,590.59
Johnson,7855.43,7593.57,10409.71,8567.85,34426.56
Klinck,15.44,15.44,15.44,15.44,61.76
McPhaden,2354.58,2320.58,2612.08,2530.58,9817.82
Meinig - Dziak,46.32,46.32,46.32,46.32,185.28
Meinig - Feely,30.88,30.88,30.88,30.88,123.52
Meinig Chaba,15.44,16.94,15.44,15.44,63.26
Meinig Former DART,207.93,220.43,214.73,209.43,852.52
Meinig GNSS GPS,13.79,13.79,13.79,13.79,55.16
Meinig SPURS2,58.46,58.46,58.46,89.21,264.59
Mordy IOTAS-ITAE,257.29,180.12,189.98,190.32,817.71
Mordy ITAE,541.08,623.83,591.08,525.83,2281.82
Stabeno,360.64,358.54,605.52,610.98,1935.68
Sutton,2316.99,2293.87,2283.36,2391.26,9285.48